### ISSUE TITLE
This code is stolen and is subject to license infringement

### ISSUE THREAD

**Issue by aelvan** [MilkshakeStudio/craft-conditions#2]
Most of the code in this repo is stolen from [Reasons](https://github.com/mmikkel/Reasons-Craft), which is distributed under an MIT license, that clearly states:

```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

Shame on you @Slgoetz

**Comment by Slgoetz** [comment]
We've fixed this issue as it was written by a contractor which lied to us.
